# crew reads teams.json version 2: partitions with their main levels, teams with units and [kit, blueprints],
# a team's partition from its session, roles overrides, and errors for anything missing or inconsistent.
. "$TESTS/lib.sh"
world

expect_ok crewpy teams; eq "$out" $'swb-1\nswb-2\nbrd-1\natl-1\napk-1'
expect_ok crewpy labels; eq "$out" $'wldn\nmadswan\nswancloud'

expect_ok crewpy env swb-1
box=$(space chuck-herdr-alpha willdan)
has "$out" "LABEL=wldn"; has "$out" "UNITS=4"; has "$out" "MACHINE=chuck-herdr-alpha"; has "$out" "SESSION=wldn-1"
has "$out" "KIT=$box/switchboard-kit/main"; has "$out" "KIT_DIR=$box/switchboard-kit"
has "$out" "BLUEPRINTS=$box/willdan-blueprints/main"
ok "a team's partition, kit and blueprints come from its session"

# Two repos named blueprints: apk-1's resolves through its session, whose space keeps agentplot's.
expect_ok crewpy env apk-1; has "$out" "LABEL=madswan"; has "$out" "BLUEPRINTS=$(space mac-studio agentplot)/blueprints/main"
ok "a repo's name is resolved to owner/name through the team's session"

edit teams "$(part wldn)['roles'] = {'planner': {'effort': 'max'}}; $(team swb-1)['roles'] = {'coder': {'model': 'claude-opus-5-5'}}"
expect_ok crewpy teams
ok "roles overrides on a team and a partition"

edit teams "$(part wldn)['roles'] = {'conductor': {'effort': 'max'}}"
expect_fail "overrides role 'conductor', which it has no definition for" crewpy teams
edit teams "$(part wldn)['roles'] = {'planner': {'effort': 'extreme'}}"
expect_fail "roles.planner.effort is 'extreme', which is no effort level" crewpy teams
edit teams "$(part wldn)['roles'] = {}; $(team swb-1)['roles'] = {'fable': {'effort': 'high'}}"
expect_fail "overrides role 'fable'" crewpy teams
edit teams "$(team swb-1)['roles'] = {}"
ok "an override naming an unknown role or effort is refused"

world_teams() { fixtures 2; }
edit teams "del $(team brd-1)['units']"
expect_fail "team brd-1 in" crewpy teams; has "$out" "has no 'units'"
world_teams
edit teams "del $(part madswan)['session']"
expect_fail "partition madswan in" crewpy teams; has "$out" "has no 'session'"
world_teams
edit teams "$(team swb-1)['coders'] = 4"
expect_fail "still has 'coders'" crewpy teams
world_teams
ok "a missing or retired field is an error"

# A team in a clients/willdan session naming afterthought's blueprints: refused, naming wldn's blueprints repos.
edit hosts "d['hosts']['mac-studio']['sessions']['wldn-5']['repos'].append('afterthought/blueprints')"
edit teams "$(team atl-1)['repos'] = ['atlas-kit', 'blueprints']"
expect_fail "names afterthought/blueprints as its blueprints repo, which is not one of clients/willdan's: WilldanGroup/willdan-blueprints" crewpy teams
world_teams
ok "a blueprints repo of another partition is refused"

edit hosts "d['hosts']['mac-studio']['sessions']['madswan-2']['partition'] = None"
expect_fail "which $(home_of mac-studio)/.config/swancloud/herdr-hosts.json puts in no partition" crewpy teams
fixtures 2
edit teams "$(team swb-1)['repos'] = ['rocs-kit', 'willdan-blueprints']"
expect_fail "does not keep rocs-kit" crewpy teams
fixtures 2
ok "a session with no partition, or a repo its space does not keep, is refused"

fixtures 1
expect_fail "must be regenerated by the machine's configuration" crewpy teams
has "$out" "crew reads only version 2"
expect_fail "must be regenerated" crew status swb-1
ok "version 1 is refused with the fix named"
